version: '2'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: nefariusmag/jenkins:2.4
    container_name: jenkins
    restart: always
    volumes:
      - ./jenkins_home/:/var/jenkins_home/
    ports:
      - 80:8080
